config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  ####################################
  # CONF
  ####################################
  devise_for :users
  
  ####################################
  # ADMIN
  ####################################
  namespace :admin do
    root 'home#index'
    resources :users
    resources :contacts
    authenticate :user, -> (user) { user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  ####################################
  # SITE
  ####################################
  
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner.rb
class Banner < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum status: [ :common, :admin ]
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < ApplicationController
  before_action :set_banner, only: %i[ show edit update destroy ]

  # GET /banners
  def index
    @banners = Banner.all
  end

  # GET /banners/1
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  def create
    @banner = Banner.new(banner_params)

    if @banner.save
      redirect_to [:admin, @banner], notice: "Banner was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /banners/1
  def update
    if @banner.update(banner_params)
      redirect_to [:admin, @banner], notice: "Banner was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /banners/1
  def destroy
    @banner.destroy
    redirect_to admin_banners_url, notice: "Banner was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banner_params
      params.require(:banner).permit(:active, :order, :name, :background, :summary, :button_name, :button_color_txt, :button_color_active, :button_color_hover, :button_link, :image)
    end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to [:admin, @contact], notice: "Contact was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to [:admin, @contact], notice: "Contact was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /contacts/1
  def destroy
    @contacts.destroy
    redirect_to admin_contacts_url, notice: "Contact was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contacts = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :description, :message, :status)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    
    # def show
    #     @user = User.find(params[:id])
    # end
    # before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user], notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: "User was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  def layout_by_resource
      @url = request.original_fullpath
      if devise_controller? and @url == '/users/sign_in' 
        'layouts/login'
      elsif devise_controller?
        'layouts/admin/application'
      else
        'layouts/admin/application'
      end
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:permission_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'application'
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/banners/_form.html.erb
<%= form_with(model: [:admin, banner], local: true) do |form| %>
  <% if banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
        <% banner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :resume %>
    <%= form.text_field :resume %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/admin/banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banners</h1>

<table>
  <thead>
    <tr>
      <th>Active</th>
      <th>Order</th>
      <th>Name</th>
      <th>Image</th>
      <th>Resume</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.active %></td>
        <td><%= banner.order %></td>
        <td><%= banner.name %></td>
        <td><%= banner.image %></td>
        <td><%= banner.resume %></td>
        <td><%= banner.description %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/admin/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Back', banners_path %>

app/views/admin/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Active:</strong>
  <%= @banner.active %>
</p>

<p>
  <strong>Order:</strong>
  <%= @banner.order %>
</p>

<p>
  <strong>Name:</strong>
  <%= @banner.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @banner.image %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @banner.resume %>
</p>

<p>
  <strong>Description:</strong>
  <%= @banner.description %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>

app/views/admin/contacts/_contact.html.erb
<div id="<%= dom_id contact %>" class="d-flex">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p class="ms-3">
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p class="ms-3">
    <strong>Subject:</strong>
    <%= contact.subject %>
  </p>

  <p class="ms-3">
    <strong>Message:</strong>
    <%= contact.summary %>
  </p>

  <p class="ms-3">
    <strong>Status:</strong>
    <%= contact.status %>
  </p>

</div>

app/views/admin/contacts/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: [:admin, @contact]) do |form| %>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% contact.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="field col">
        <%= form.label :status %>
        <%= form.number_field :status, :class => 'form-control mb-3' %>
      </div>
      <div class="field col">
        <%= form.label :phone %>
        <%= form.text_field :phone, :class => 'form-control mb-3' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, :class => 'form-control mb-3' %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, :class => 'form-control mb-3' %>
    </div>

    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject, :class => 'form-control mb-3' %>
    </div>

    <div class="field">
      <%= form.label :summary %>
      <%= form.text_area :summary, :class => 'form-control mb-3' %>
    </div>

    <div class="actions">
      <%= form.submit :class => "btn-DARK-BLUE border-0", :style => "float: right;" %>
    </div>
  <% end %>
</div>

app/views/admin/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contacts %>

<%= link_to 'Show', [:admin, @contacts] %> |
<%= link_to 'Back', admin_contacts_path %>

app/views/admin/contacts/index.html.erb
<div class="container mt-5">
  <p id="notice"><%= notice %></p>

  <h1 class="serif mb-3">Contacts</h1>

  <div class="card_DFLT">
    <table>
      <thead>
        <tr>
          <th>Status</th>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Subject</th>
          <th>Summary</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.status %></td>
            <td><%= contact.name %></td>
            <td><%= contact.phone %></td>
            <td><%= contact.email %></td>
            <td><%= contact.subject %></td>
            <td><%= contact.summary %></td>
            <td class="text-center"><%= link_to 'Show', [:admin, contact], :class => "btn-outline-light btn" %></td>
            <td class="text-center"><%= link_to 'Edit', edit_admin_contact_path(contact), :class => "btn-outline-light btn" %></td>
            <td class="text-center"><%= link_to 'Destroy', [:admin, contact], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-outline-light btn" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to '+ New Contact', new_admin_contact_path, :class => "btn-DARK-BLUE" %>
</div>

app/views/admin/contacts/new.html.erb
<div class="container mt-5">
    <h1 class="serif">New Contact</h1>

    <div class="row">
        <%= render 'form', contact: [:admin, @contact] %>
        <div style="padding: 0px 12px;">
            <%= link_to '<- Back', admin_contacts_path, :class => "btn-LIGHT-BLUE w-auto" %>
        </div>
    </div>

</div>

app/views/admin/contacts/show.html.erb
<div class="container-xxl mt-5 ">
  <p style="color: green"><%= notice %></p>

  <%= render @contacts %>

  <div class="d-flex">
    <%= link_to "Edit this contact", edit_admin_contact_path(@contacts), :class => "btn-DARK-BLUE me-3" %>
    <%= link_to "Back to contacts", admin_contacts_path, :class => "btn-LIGHT-BLUE me-3" %>

    <%= button_to "Destroy this contact", [:admin, @contacts], method: :delete, :class => 'btn btn-danger' %>
  </div>
</div>

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user]) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>" class="d-flex justify-content-between w-75">
  <!--p class="ms-3">
    <strong>Name:</strong>
    < %= user.name %>
  </p-->

  <p class="me-3">
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p class="ms-3">
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <!--p class="ms-3">
    <strong>Password confirmation:</strong>
    <%= user.password_confirmation %>
  </p-->

</div>

app/views/admin/users/edit.html.erb
<div class="container mt-5 text-white">
  <h1>Editing user</h1>

  <%= render "form", user: @user %>

  <br>

  <div>
    <%= link_to "Show this user", @user %> |
    <%= link_to "Back to users", users_path %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container mt-5">
  <p style="color: green"><%= notice %></p>

  <h1 class="serif mb-4">Users</h1>

  <div id="users" class="mt-3">
    <% @users.each do |user| %>
    <div class="d-flex justify-content-between mt-2">
      <%= render user %>
      <p>
        <%= link_to "Show this user", [:admin, user], :class => 'btn-LIGHT-BLUE' %>
      </p>
    </div>
    <% end %>
  </div>

  <%= link_to "+ New user", new_admin_user_path, :class => 'btn-DARK-BLUE' %>
</div>

app/views/admin/users/new.html.erb
<div class="container mt-5">
  <h1>New user</h1>

  <%= render "form", user: [:admin, @user] %>

  <br>

  <div>
    <%= link_to "Back to users", admin_users_path %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-5">
  <p style="color: green"><%= notice %></p>

  <%= render @user %>

  <div>
    <%= link_to "Edit this user", edit_admin_user_path(@user) %> |
    <%= link_to "Back to users", admin_users_path %>

    <%= button_to "Destroy this user", [:admin, @user], method: :delete, :class => 'btn btn-danger' %>
  </div>
</div>

app/views/home/_carousel.html.erb


<% if !user_signed_in? %>
    <div class="carousel_div">
        <%= image_tag("carousel", {:style => "width:100%; height: 337px; object-fit: cover;"}) %>
        <div class="z-index ">
            <h1 class="serif">Background Job Project</h1>
            <h1 class="serif">Ruby on Rails</h1>
        </div>
    </div>
<% end %>

<% if user_signed_in? %>
    <div class="carousel_div">
        <div class="z-index ">
            <h1 class="serif textDarkBlue">Welcome to my Project!</h1>
        </div>
    </div>
<% end %>

app/views/home/_first_section.html.erb
<div class="container d-flex flex-wrap mt-5 flex-column justify-content-between" >

    <div class="d-flex justify-content-start flex-column">
        <h1 class="serif">First Things First</h1>
        <h3 class="serif mt-4">Start Redis</h3>
        <p>Run this to start Redis server for a perfect running application with Sidekiq.</p>
        <div class="d-flex">
            <input type="text" value="sudo service redis-server start" id="copyFunction" class="code m-0 border-0" style="width: 21rem;">
            <button onclick="copyFunction()" class="btn-WHITE ms-3">Copy</button>
        </div>
    </div>

    <div class="d-flex justify-content-end align-items-end flex-column">
        <h3 class="serif">Connect to Redis</h3>
        <p>You can test that your Redis server is running by connecting with the Redis CLI:</p>
        <div class="d-flex code w-25 flex-column" style="height: 5.4rem;">
            <p class="" >
            redis-cli</br>
            127.0.0.1:6379> ping</br>
            PONG
            </p>
        </div>
    </div>
    
    <h4 class="serif mt-3">You can solve your doubts by yourself at <a href="https://redis.io/docs/getting-started/installation/install-redis-on-windows/" aria-current="page">Redis CLI</a>.</h4>

    <div class="card mt-4" style="height: 265px;">
        <div class="card-body d-flex flex-column" style="height: 226px;">
            <h2 class="serif mb-3">Simple, efficient background processing for Ruby.</h2>
            <p class="serif mb-3" style="font-size:16px!important; width: 50%;">Sidekiq uses threads to handle many jobs at the same time in the same process. It does not require Rails but will integrate tightly with Rails to make background processing dead simple.</p>
            <p class="serif fw-bold" style="font-size:16px!important;">
                <a href="https://github.com/mperham/sidekiq" class="text-white">
                    View the docs
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
                    </svg>
                </a>
            </p>
            
            <%= image_tag("https://www.digitalocean.com/_next/static/media/cloudJourneyImage.954519ea.svg", {:style => "z-index: 22; position: relative; top: -124px; left: 704px; width: 557px;"}) %>
        </div>
    </div>

    <div class="d-flex flex-column align-items-center justify-content-center" style="margin: 5rem 0">
        <h1 class="serif fw-bold">Have any idea to improve here?</h1>
        <h5 class="serif mt-3">Get in touch with me by an email or something like that.</h5>
    </div>
</div>
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <svg class="bd-placeholder-img rounded me-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#007aff"></rect></svg>
    <strong class="me-auto">Successfully Copied!</strong>
    <small>just now</small>
    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close" onclick="unDisplayToast()"></button>
  </div>
  <div class="toast-body">
    Wow, you just copied the text!
  </div>
</div>

app/views/home/_not_signed_in_home.html.erb
<%= render "home/carousel" %>
<%= render "home/second_section" %>

app/views/home/_second_section.html.erb
<div class="container d-flex flex-wrap mt-5 flex-column align-items-center" >
    <h1 class="serif">Make sure you are logged in for admin access.</h1>
    <p class="code mt-3 d-flex align-items-center justify-content-center" style="width:25rem;">Login with an admin account for more!</p>
</div>

app/views/home/_signed_in_home.html.erb
<%= render "carousel" %>
<%= render "first_section" %>

app/views/home/index.html.erb
<% if !user_signed_in? %>
    <%= render "not_signed_in_home" %>
<% end %>

<% if user_signed_in? %>
    <%= render "signed_in_home" %>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
       <title>Ruby on Rails | RoR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="icon" type="image/png" href="https://global.discourse-cdn.com/rubyonrails/optimized/1X/bc68acbc8c022726e69f980e00d6811212d9378d_2_32x32.ico">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </head>

  <body>
    <% unless current_page?(user_session_path) || current_page?(new_user_session_path)  || current_page?(new_user_registration_path)  || current_page?(user_registration_path)  || current_page?(new_user_password_path)%>
      <%= render "layouts/site/navbar" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails | RoR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="icon" type="image/png" href="https://global.discourse-cdn.com/rubyonrails/optimized/1X/bc68acbc8c022726e69f980e00d6811212d9378d_2_32x32.ico">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </head>

  <body>
    <% unless current_page?(user_session_path) || current_page?(new_user_session_path)  || current_page?(new_user_registration_path)  || current_page?(user_registration_path)  || current_page?(new_user_password_path)%>
      <%= render "layouts/site/navbar" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/site/_navbar.html.erb
<div style="position: sticky; top: 0; z-index: 999999;">
  <nav class="py-1 w-100" style="background-color:#081B4B;">
      <div class="container d-flex flex-wrap align-items-center justify-content-between">
        <p class="serif text-white m-0" style="font-size:14px">
          Hello there! Make sure you have an admin account for real access. Learn more
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
          </svg>
        </p>
        
        <%= link_to "Support", admin_sidekiq_web_path, :class => "nav-item nav-link link-dark px-2" %>

        <p class="serif text-white m-0" style="font-size:14px">
          Get Support 
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
          </svg>
        </p>
      </div>
  </nav>
  <nav class="py-2 bg-light border-bottom w-100">
      <div class="container d-flex flex-wrap">
        <ul class="nav me-auto">
          <li class="nav-item"><a href="<%= root_path %>" class="nav-link link-dark px-2 active fw-bold" aria-current="page">Rails Project</a></li>
          <li class="nav-item"><a href="<%= root_path %>" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
          <% if user_signed_in? %>
            <%= link_to "Sidekiq", admin_sidekiq_web_path, :class => "nav-item nav-link link-dark px-2" %>
            <%= link_to "Users", admin_users_url, :class => "nav-item nav-link link-dark px-2" %>
            <%= link_to "Contacts", admin_contacts_path, :class => "nav-item nav-link link-dark px-2" %>
          <% end %>
        </ul>
        <ul class="nav">        
          <% if user_signed_in? %> 
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "nav-item nav-link btn-DARK-BLUE" %>
          <% else %>
              <%= link_to "Login", new_user_session_path, :class => "nav-item nav-link link-dark px-2 me-3" %>
              <%= link_to "Sign in", new_user_registration_path, :class => "nav-item nav-link btn-LIGHT-BLUE" %>
          <% end %>
        </ul>
      </div>
  </nav>
</div>